pipeline {
    agent any

    stages {
        stage('Clean Workspace') {
            steps {
                // Deletes entire workspace before starting
                deleteDir()
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                // Change to the folder containing pom.xml
                dir('new-java-project') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Start App') {
            steps {
                sshagent (credentials: ['1f606acc-0968-4f43-854a-89eca8d4a32d']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ec2-user@54.226.118.108 \\
                    'nohup java -jar /home/ec2-user/workspace/new-java-project/target/new-java-project-1.0-SNAPSHOT.jar > /home/ec2-user/app.log 2>&1 < /dev/null &'
                    """
                }
            }
        }
    }
}
